### ISSUE TITLE
aws-sdk should be moved to a peerDependency

### ISSUE THREAD

**Issue by joelnet** [jesseditson/winston-sns#11]
When deploying code to AWS Lambda, our project requires us to omit the `aws-sdk` directory from node_modules. In my project.json, it is listed as a `devDependecy`, so I can run `npm prune --production` to remove all `devDependencies`.

But because `aws-sdk` is listed in the `dependencies` for `winston-sns`, it doesn't get pruned from the `node_modules`.

Also, the dependencies in the `aws-sdk` package are also included and cannot be auto-pruned.

I would like to propose moving the `aws-sdk` from the `dependencies` into the `peerDependencies` and adding a note to self-install the peer dependency in the README when not running in a lambda environment.

Cheers!

**Comment by jesseditson** [comment]
I haven't used lambda a ton, so I'm curious what the issue with having aws-sdk is - is this true for all lambda projects? My feeling on this is that it breaks the intended behavior (you should be able to run `npm install` and require this package, and it should work - this would add an additional step for all users if I understand it correctly).

Perhaps a more appropriate fix would be to add a postinstall script that checked if it was running in lambda and remove the aws-sdk dep? If this is specific to your environment, I'd recommend adding a postinstall to your parent package.json and avoiding modifying this dep directly. If you would expect this to effect all lambda users, I believe a PR to prune the dep post install here would be a better solution.

Let me know if I'm misunderstanding! Also, since I no longer use any of this code in prod, I'll leave any final decision making to @MattCBowman since he owns the current majority of code.

**Comment by joelnet** [comment]
It's complicated.

It is recommended to not include the `aws-sdk` in your package when uploading to the Lambda environment.

Adding the `aws-sdk` to `dependencies` adds 39M of node_modules. This size becomes significant in a Lambda.

```bash
$ du -sh node_modules/
 39M	node_modules/

$ ll node_modules/
drwxr-xr-x - user 23 Jan 14:54 .bin
drwxr-xr-x - user 23 Jan 14:54 aws-sdk
drwxr-xr-x - user 23 Jan 14:54 base64-js
drwxr-xr-x - user 23 Jan 14:54 buffer
drwxr-xr-x - user 23 Jan 14:54 events
drwxr-xr-x - user 23 Jan 14:54 ieee754
drwxr-xr-x - user 23 Jan 14:54 isarray
drwxr-xr-x - user 23 Jan 14:54 jmespath
drwxr-xr-x - user 23 Jan 14:54 punycode
drwxr-xr-x - user 23 Jan 14:54 querystring
drwxr-xr-x - user 23 Jan 14:54 sax
drwxr-xr-x - user 23 Jan 14:54 url
drwxr-xr-x - user 23 Jan 14:54 uuid
drwxr-xr-x - user 23 Jan 14:54 xml2js
drwxr-xr-x - user 23 Jan 14:54 xmlbuilder
```

A post install script is complicated, because you would have to recursively remove dependencies that are only used by the `aws-sdk` and it's dependencies (also recursively).

Our current process for deploying to a Lamda using`winston-sns` is like this:

1. `npm install winston-sns`
2. edit `./node_modules/winston-sns/package.json` and remove `aws-sdk` from `dependencies`.
3. `npm install`
4. deploy

When `aws-sdk` is listed as a `peerDependency`, the user would receive a warning:
```bash
npm WARN winston-sns@0.2.4 requires a peer of aws-sdk@^2.1.x but none is installed. You must install peer dependencies yourself.
```

Using `npm remove aws-sdk` only removes the the `aws-sdk` folder and does not remove any of the `aws-sdk` dependencies that have also been installed.

Unfortunately there's really no perfect solution.

Either there is a hack for all Lambda users or all non-Lambda users need an additional step of `npm install aws-sdk`. 😞 

But this is the purpose of the `peerDependencies`. Putting the responsibility on the importing package to install specific dependencies.

**Comment by jesseditson** [comment]
`peerDependencies` is generally useful (IMO) in libraries that don't want to explicitly require a version of a dependency library, but are instead expected to be useless outside of an environment that does not have the dep - e.g. a supplemental react library that does not want the user to have to use a specific minor/patch version, but does require that there is any version of react installed to work.

IMO this wouldn't fall into the acceptable use category of `peerDependencies`, as it would break the ability to use this library "out of the box" (e.g. just installing winston-sns), since I don't think it's reasonable to expect that any project that uses this library would be expected to also list aws-sdk as a dep. (Which is to say, this could be the only dependency that uses aws-sdk in codebase, and this dep would still be useful. Not so the case for the react example above.)

That said, I think `npm uninstall` may do what you need. I am unfamiliar with lambda and your deploy techniques, but I'd expect that if your deploy just sends the entire local directory, you could do add this to your `package.json`

```json
"scripts": {
	"deploy": "npm uninstall aws-sdk && ./scripts/deploy.sh && npm i"
}
```

which would just remove the dep from your local node_modules while `scripts/deploy.sh` ran. In any case, I don't think that the existence of aws-sdk on a specific deploy target would really fall under the responsibilities of this library, so I'd recommend solving this on a case by case basis. Let me know if I'm making an errant assumption that seems like it would warrant this handling specific deploy targets!

**Comment by joelnet** [comment]
**This has no effect:**

```bash
$ npm install winston-sns
$ npm uninstall aws-sdk
```

`aws-sdk`, and also it's dependencies (recursively), cannot be removed because it is not a dependency of the main `package.json`, but a dependency of `winston-sns`.

**This works:**

```bash
$ npm install winston-sns
$ cd node_modules/winston-sns
$ npm uninstall aws-sdk
$ cd ../..
$ npm install

removed 122 packages and audited 18 packages in 1.122s
```

But this is fragile any npm upgrade of `winston-sns` will also add it's dependencies back.

`node_modules` with `aws-sdk`: 39M
`node_modules` sans `aws-sdk`: 268K

So the deploy script would have to be:

```json
"scripts": {
	"deploy": "cd node_modules/winston-sns && npm uninstall aws-sdk && cd ../.. && npm install && ./scripts/deploy.sh"
}
```

> Let me know if I'm making an errant assumption that seems like it would warrant this handling specific deploy targets!

It's a complicated problem. Because the solution I am suggesting would be a breaking change. It would require adding `aws-sdk` to the main `package.json` for all projects that use `winston-sns`. The install instructions would have to be changed to `npm install winston-sns aws-sdk`.

Maybe just a note in the README for AWS Lambda would be sufficient.

**Comment by jesseditson** [comment]
Makes sense. To be clear, I'm not open to a peerDependencies approach, as it would diverge from the basic assumptions that I make about npm packages, in that I can `npm install` then `import/require` them and they work.

However, I would be happy to merge a PR with a note in the `README.md` for lambda users mentioning how to remove large dependencies (this does not seem specific to this library, but is useful information regardless)!

Thanks for hanging with me on this! I think I understand the issue now and will close.
